3_trimestre/django/Adocao/Adocao/urls.py
from django.contrib import admin

from django.urls import path, include
# include vai incluir as urls dos seus módulos no projeto

urlpatterns = [
    path('admin/', admin.site.urls),
    # URL base para as importações e o app
    # neste caso, não precisa digitar nada a mais para
    # acessar as urls criadas no app animais
    path('', include('animais.urls'))
]

3_trimestre/django/Adocao/animais/urls.py
from django.urls import path

# importa tudo que tem no views.py do app "animais"
from .views import *
# . indica para o python buscar o views dentro deste diretório
# * indica para importar tudo de lá

urlpatterns = [
    #   ( endereço, método da view, nome da url )
    path('', Index.as_view(), name="index" ),
    path('ajuda/', Ajuda.as_view(), name="ajuda"),
    path('contato/', Contato.as_view(), name="contato"),
    path('sobre/', Sobre.as_view(), name="sobre"),
    path('procurar/', Procurar.as_view(), name="procurar"),

    path('nova/cidade/', CidadeCreate.as_view(), name='inserir-cidade'),
    path('editar/cidade/<int:pk>/', CidadeUpdate.as_view(), name='editar-cidade'),
    path('excluir/cidade/<int:pk>/', CidadeDelete.as_view(), name='excluir-cidade'),
    path('listar/cidades/', CidadeList.as_view(), name="listar-cidades"),

    path('nova/pessoa/', PessoaCreate.as_view(), name='inserir-pessoa'),
    path('editar/pessoa/<int:pk>', PessoaUpdate.as_view(), name='editar-pessoa'),
    path('excluir/pessoa/<int:pk>', PessoaDelete.as_view(), name='excluir-pessoa'),
    path('listar/pessoas/', PessoaList.as_view(), name="listar-pessoas"),
]

3_trimestre/django/Adocao/animais/models.py
from django.db import models

# Create your models here.
# Todas as classes extendem a classe models.Model
class Cidade(models.Model):
    # nome_do_atributo = tipoDele(características)
    nome = models.CharField(max_length=50)
    estado = models.CharField(max_length=2, help_text='Informe apenas a sigla')
    
    # apenas para imprimir o objeto conforme abaixo
    def __str__(self):
        # Paranavaí (PR)
        return self.nome + ' (' + self.estado + ')'

class Pessoa(models.Model):
    nome = models.CharField(max_length=50, help_text='Nome completo')
    email = models.CharField(max_length=50)
    nascimento = models.DateField('Data de Nascimento')
    # Chave estrangeira deve informar a Classe e a relação ao excluir
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)

    def __str__(self):
        # Faz um cast da data para string
        return self.nome + ' - ' + str(self.nascimento)

3_trimestre/django/Adocao/animais/views.py
# Uma classe simples para exibir uma página simples
from django.views.generic import TemplateView
# Serve para páginas que só tem HTML e talvez alguma consulta
# para listar coisas do banco

# Importar os modelos
from .models import *

# Importar os métodos View para inserir, alterar e excluir
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Importar a View para listar classes
from django.views.generic.list import ListView

# Importar a função para gerar o endereço de nossas URLS inteiras
from django.urls import reverse_lazy


# Página inicial
class Index(TemplateView):
    # Define qual o arquivo HTML vai ser usado para exibir esta página
    template_name = "pagina_inicial.html" # deve estar na pasta templates


# Página de ajuda
class Ajuda(TemplateView):
    # Define qual o arquivo HTML vai ser usado para exibir esta página
    template_name = "ajuda.html" # deve estar na pasta templates


class Contato(TemplateView):
    template_name = 'contato.html'


class Sobre(TemplateView):
    template_name = 'sobre.html'


class Procurar(TemplateView):
    template_name = 'procurar.html'


class CidadeCreate(CreateView):
    # identificar o modelo
    model = Cidade
    # Define para onde vai redirecionar depois de inserir
    success_url = reverse_lazy('listar-cidades')
    # Define qual o template vai ser usado
    template_name = 'form.html'
    # Define quais campos vão esta no formulário
    fields = ['nome', 'estado']


class CidadeUpdate(UpdateView):
    model = Cidade
    success_url = reverse_lazy('listar-cidades')
    template_name = 'form.html'
    fields = ['nome', 'estado']


class CidadeDelete(DeleteView):
    model = Cidade
    success_url = reverse_lazy('listar-cidades')
    template_name = 'form_delete.html'


class CidadeList(ListView):
    model = Cidade
    template_name = 'cidade_list.html'


class PessoaCreate(CreateView):
    model = Pessoa
    success_url = reverse_lazy('listar-pessoas')
    template_name = 'form.html'
    fields = ['nome', 'email', 'nascimento', 'cidade']


class PessoaUpdate(UpdateView):
    model = Pessoa
    success_url = reverse_lazy('listar-pessoas')
    template_name = 'form.html'
    fields = ['nome', 'email', 'nascimento', 'cidade']


class PessoaDelete(DeleteView):
    model = Pessoa
    success_url = reverse_lazy('listar-pessoas')
    template_name = 'form_delete.html'


class PessoaList(ListView):
    model = Pessoa
    template_name = 'pessoa_list.html'

3_trimestre/django/Adocao/animais/templates/ajuda.html
{% extends 'modelo.html' %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row pt-5">

    <div class="col-sm p-5">

      <h2>Ajuda</h2>

      <p>
        Está é a página de ajuda...
      </p>

    </div>

    <div class="col-sm p-5">

      Bla bla bla

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/cidade_list.html
{% extends 'modelo.html' %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4">

      <h2 class="border-bottom">
        Lista de Cidades
        <a href="{% url 'inserir-cidade' %}" class="float-right btn btn-primary btn-sm">
          <i class="fa fa-plus" aria-hidden="true"></i>
          Adicionar
        </a>
      </h2>

      <table class="table table-striped mt-4">

        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Opções</th>
        </tr>

        {% for cidade in object_list %}

          <tr>
            <td>{{cidade.id}}</td>
            <td>{{cidade.nome}}</td>
            <td>

              <a href="{% url 'editar-cidade' cidade.id %}" class="btn btn-secondary btn-sm">
                <i class="fa fa-pencil" aria-hidden="true"></i>
              </a>

              <a href="{% url 'excluir-cidade' cidade.id %}" class="btn btn-danger btn-sm">
                <i class="fa fa-times" aria-hidden="true"></i>
              </a>

            </td>
          </tr>

        {% empty %}
            <tr>
              <td colspan="3">Nenhuma cidade cadastrada!</td>
            </tr>
        {% endfor %}

      </table>

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/contato.html
{% extends 'modelo.html' %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4">

      <h2>Contato</h2>

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/form.html
{% extends 'modelo.html' %}

{% load bootstrap4 %}
{% load static %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4">

      <h2>Cadastro</h2>

      <form method="post">
        {% csrf_token %}

        {% bootstrap_form form %}

        <button type="submit" class="btn btn-primary">
          Cadastrar
        </button>

      </form>

    </div>

  </div>

</div>

{% endblock %}

{% block js %}
<script src="{% static 'js/jquery.mask.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {

    $("#id_nascimento").mask('00/00/0000');
    $("#id_nome").focus();

  });
</script>
{% endblock %}

3_trimestre/django/Adocao/animais/templates/form_delete.html
{% extends 'modelo.html' %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4">

      <h2>Excluir registro</h2>

      <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-danger">
          Excluir
        </button>

      </form>

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/modelo.html
<!-- Carregar o módulo e as referências lá para o static -->
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Adote um animal!</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css'  %}" rel="stylesheet">

    <!-- Importar o Font awesome -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Cria um bloco com o HTML a seguir... -->
    {% block menu %}

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">AdoçãoNET</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
           <li class="nav-item">
             <a class="nav-link" href="{% url 'index' %}">
               <i class="fa fa-home" aria-hidden="true"></i>
               Home
               <span class="sr-only">(current)</span></a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'procurar' %}">
               <i class="fa fa-search" aria-hidden="true"></i>
               Procurar
             </a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'contato' %}">
               <i class="fa fa-comments" aria-hidden="true"></i>
               Contato
             </a>
           </li>

           <li class="nav-item">
             <a class="nav-link" href="{% url 'sobre' %}">
               <i class="fa fa-align-left" aria-hidden="true"></i>
               Sobre
             </a>
           </li>

           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-plus-circle" aria-hidden="true"></i>
              Cadastros
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'listar-cidades' %}">Cidade</a>
              <a class="dropdown-item" href="{% url 'listar-pessoas' %}">Pessoa</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Animal</a>
              <a class="dropdown-item" href="#">Tipo</a>
            </div>
          </li>

         </ul>
       </div>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ajuda' %}">
                <i class="fa fa-info-circle" aria-hidden="true"></i>
                Ajuda
              </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="#">
                <i class="fa fa-sign-in" aria-hidden="true"></i>
                Login
              </a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %}


    {% block cabecalho %}
    <header class="masthead text-center text-white">
      <div class="masthead-content">
        <div class="container">
          <h1 class="masthead-heading mb-0">Adote um animal</h1>
          <h2 class="masthead-subheading mb-0">ou divulgue aqui se você quer doar algum!</h2>

          <!-- <a href="#" class="btn btn-primary btn-xl rounded-pill mt-5">
            <i class="fa fa-user-plus" aria-hidden="true"></i>
            Cadastre-se
          </a>

          <br>

          <button id="btn-procurar" class="btn btn-info btn-xl rounded-pill mt-5">
            <i class="fa fa-search" aria-hidden="true"></i>
            Procurar
          </button>

          <br> -->

          <!-- <div id="div-procurar" style="display: none;" class="input-group input-group-lg mt-5 w-25 mx-auto">
            <input type="text" class="form-control" placeholder="Procure um..." aria-label="Procure um..." aria-describedby="button-addon2">
            <div class="input-group-append">
              <button class="btn btn-dark dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Tipo</a>
                <a class="dropdown-item" href="#">Raça</a>
              </div>
            </div>
          </div> -->

        </div>
      </div>
      <div class="bg-circle-1 bg-circle"></div>
      <div class="bg-circle-2 bg-circle"></div>
      <div class="bg-circle-3 bg-circle"></div>
      <div class="bg-circle-4 bg-circle"></div>
    </header>
    {% endblock %}


    {% block conteudo %}
    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 order-lg-2">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-lg-6 order-lg-1">
            <div class="p-5">
              <h2 class="display-4">For those about to rock...</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-lg-6">
            <div class="p-5">
              <h2 class="display-4">We salute you!</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-6 order-lg-2">
            <div class="p-5">
              <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
            </div>
          </div>
          <div class="col-lg-6 order-lg-1">
            <div class="p-5">
              <h2 class="display-4">Let there be rock!</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- fim da parte branca (conteúdo) do meu layout -->
    {% endblock %}

    {% block rodape %}
    <!-- Footer -->
    <footer class="py-3 bg-black">
      <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; Zottesso.com.br - 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>

    <!-- Só existe para garantir que o bloco js vai ser executado
    depois de importar as bibliotecas -->
    {% block js %}
    <script type="text/javascript">
      $(document).ready(function() {

        $("#btn-procurar").click(function(event) {
          /* Act on the event */
          $("#div-procurar").fadeToggle();

        });

      });
    </script>
    {% endblock %}



  </body>

</html>

3_trimestre/django/Adocao/animais/templates/pagina_inicial.html
<!-- Faz esta página virar uma herança de modelo -->
{% extends 'modelo.html' %}


{% block conteudo %}

<div class="container">

  <div class="row">

    <div class="col-sm p-4">

      <h3>Página inicial</h3>

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/pessoa_list.html
{% extends 'modelo.html' %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4">

      <h2 class="border-bottom">
        Lista de Pessoas
        <a href="{% url 'inserir-pessoa' %}" class="float-right btn btn-primary btn-sm">
          <i class="fa fa-plus" aria-hidden="true"></i>
          Adicionar
        </a>
      </h2>

      <table class="table table-striped mt-4">

        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Email</th>
          <th>Cidade</th>
          <th>Opções</th>
        </tr>

        {% for pessoa in object_list %}

          <tr>
            <td>{{pessoa.id}}</td>
            <td>{{pessoa.nome}}</td>
            <td>{{pessoa.email}}</td>
            <td>{{pessoa.cidade}}</td>
            <td>

              <a href="{% url 'editar-pessoa' pessoa.id %}" class="btn btn-secondary btn-sm">
                <i class="fa fa-pencil" aria-hidden="true"></i>
              </a>

              <a href="{% url 'excluir-pessoa' pessoa.id %}" class="btn btn-danger btn-sm">
                <i class="fa fa-times" aria-hidden="true"></i>
              </a>

            </td>
          </tr>

        {% empty %}
            <tr>
              <td colspan="3">Nenhuma cidade cadastrada!</td>
            </tr>
        {% endfor %}

      </table>

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/procurar.html
{% extends 'modelo.html' %}

{% load static %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4 text-center">

      <!-- <h2 class="display-4 text-info">Procurar</h2> -->

      <img class="w-100" src="{% static 'img/animais_bg.jpg' %}" alt="">

      <form method="get">
        <div class="form-group">
          <!-- <label for="procurar">Nome ou Raça</label> -->
          <input type="text" class="border-warning border-2 text-dark text-center form-control form-control-lg" id="procurar" placeholder="Digite raça ou o tipo do animal" required/>
          <small id="procurarHelp" class="form-text text-muted">Ex: vira lata, cachorro, tatu, persa.</small>
        </div>

        <button type="submit" class="btn btn-primary btn-lg my-3">
          <i class="fa fa-search" aria-hidden="true"></i>
          Procurar
        </button>
      </form>

    </div>

  </div>

</div>

{% endblock %}

3_trimestre/django/Adocao/animais/templates/sobre.html
{% extends 'modelo.html' %}

{% block cabecalho %}

{% endblock %}

{% block conteudo %}

<div class="container">

  <div class="row mt-5">

    <div class="col-sm p-3 mt-4">

      <h2>Sobre</h2>

    </div>

  </div>

</div>

{% endblock %}